version: 0.2

env:
  variables:
    IMAGE_TAG: "no_version"
    PROJECT_NAME: "no_name"

phases:
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
        - export IMAGE_TAG=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        - export PROJECT_NAME=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='artifactId']/text()" pom.xml)
        - sed -i "s/REPLACE_PROJECT_NAME/$PROJECT_NAME/g" stop_server.sh
        - sed -i "s/REPLACE_PROJECT_NAME/$PROJECT_NAME/g" start_server.sh
        - sed -i "s/REPLACE_PROJECT_NAME/$PROJECT_NAME/g" check_service.sh
        - sed -i "s/REPLACE_PROJECT_NAME/$PROJECT_NAME/g" prepare_stuff.sh
        - sed -i "s/REPLACE_PROJECT_NAME/$PROJECT_NAME/g" appspec.yml
        - export IMAGE_NAME=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME:$IMAGE_TAG
        - sed -i "s#REPLACE_IMAGE_NAME#$IMAGE_NAME#g" docker-compose.swarm.yml
        - sed -i "s#REPLACE_IMAGE_NAME#$IMAGE_NAME#g" docker-compose.testing.yml
    build:
      commands:
        - echo Build started on `date` for $PROJECT_NAME version $IMAGE_TAG
        - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME:latest .
        - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME:$IMAGE_TAG
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME:$IMAGE_TAG
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME:latest

artifacts:
  files:
    - 'stop_server.sh'
    - 'start_server.sh'
    - 'check_service.sh'
    - 'prepare_stuff.sh'
    - 'appspec.yml'
    - 'docker-compose.testing.yml'
    - 'docker-compose.swarm.yml'
