version: '3.1'

services:

  web:
    image: wordpress
    ports:
      - 80
    environment:
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ../wp-${DEPLOYMENT_GROUP_NAME}-files/wp-content:/var/www/html/wp-content
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

networks:
  default:
    external:
      name: nginx-proxy
